language: ruby
rvm:
  - 2.1.0
script: bundle exec rspec spec
before_script:
  - psql -c 'create database scirate_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - RAILS_ENV=test bundle exec rake db:setup
