language: ruby
cache: bundler
rvm:
  - 2.1.4
bundler_args: -j4 --without development production --quiet
script:
  - RAILS_ENV=test bundle exec rake db:setup
  - bundle exec rspec spec
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get purge elasticsearch
  - wget -O /tmp/elasticsearch.deb https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.3.2.deb
  - sudo dpkg -i /tmp/elasticsearch.deb
  - sudo service elasticsearch start
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database scirate_test;' -U postgres
notifications:
  email:
    - scirate@mispy.me
services:
  - elasticsearch
